version: "3.8"

services:
  mongo-user:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-user-data:/data/db

  mongo-fee:
    image: mongo:7
    ports:
      - "27019:27017"
    volumes:
      - mongo-fee-data:/data/db

  mongo-payment:
    image: mongo:7
    ports:
      - "27020:27017"
    volumes:
      - mongo-payment-data:/data/db

  mongo-otp:
    image: mongo:7
    ports:
      - "27021:27017"
    volumes:
      - mongo-otp-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # dashboard quản lý queue: http://localhost:15672 (guest/guest)

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    env_file: ./user-service/.env
    depends_on:
      - mongo-user

  fee-service:
    build: ./fee-service
    ports:
      - "3002:3002"
    env_file: ./fee-service/.env
    depends_on:
      - mongo-fee

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"
    env_file: ./payment-service/.env
    depends_on:
      - mongo-payment
      - user-service
      - fee-service
      - otp-service

  otp-service:
    build: ./otp-service
    ports:
      - "3004:3004"
    env_file: ./otp-service/.env
    depends_on:
      - mongo-otp
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file: ./api-gateway/.env
    depends_on:
      - user-service
      - fee-service
      - payment-service

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  mongo-user-data:
  mongo-fee-data:
  mongo-payment-data:
  mongo-otp-data:
